### ISSUE TITLE
0.1.0 or 1.0.0 as initial version?

### ISSUE THREAD

**Issue by LostCrew** [ecosia/vue-strip-html#24]
Any preference? I'd prefer `0.1.0` which marks it as `unstable` on npms and `beta` on other systems. Just because there may surely be some small core tweaks to do before we deem it "stable".

**Comment by axlwaii** [comment]
I would prefer 1.0.0 because it is production code. Also it has gone through some iterations already. I fear it will stay at 0.1.0 even though it is pretty much a 1.0.0

**Comment by LostCrew** [comment]
Good point!

**Comment by jakubfiala** [comment]
yeah I think Markus said it pretty well, agree with 1.0.0

**Comment by jakubfiala** [comment]
but also let's make sure we're really sure about the current public API of the plugin. It would be a shame to release v1 and immediately have to change it afterwards :P

**Comment by LostCrew** [comment]
`1.0.0` will be
